export const keywords = [
  'aplicativo de aprender inglês',
  'melhor aplicativo para aprender inglês',
  'aprender inglês para iniciantes',
  'melhorar o vocabulário em inglês',
  'aprender gramática inglesa',
  'praticar conversação em inglês',
  'aprender inglês online',
  'recursos para aprender inglês',
  'jogos para aprender inglês',
  'aprender inglês grátis',
  'aprender inglês para + objetivo específico (por exemplo, negócios, viagens, TOEFL)',
  'aplicativo de pronúncia em inglês',
  'inglês para crianças',
  'exercícios de gramática inglesa',
  'construtor de vocabulário em inglês',
  'compreensão auditiva em inglês',
  'prática de conversação em inglês',
  'inglês para falantes de [idioma nativo, por exemplo, espanhol]',
  'como melhorar a fala em inglês',
  'melhores aplicativos para aprender gramática inglesa grátis',
  'maneiras divertidas e eficazes de aprender vocabulário em inglês',
  'dicas para iniciantes aprendendo inglês',
  'recursos para aprender conversação em inglês para viagem',
];
